spring:
  profiles:
      active: dev #使用本地配置，要使用git存储改为git即可
  application:
    name: User-A
  datasource:
    url: jdbc:mysql://localhost:3306/doupin?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 100 #连接池初始化大小
      min-idle: 100 #最小空闲连接数
      max-active: 100 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid